<?php

namespace Oidnus\WalletBundle\Repository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getReport($username,$date){

		return $this->getEntityManager()
			->createQuery('
                SELECT t
                FROM OidnusWalletBundle:Transaction t
                WHERE t.username = :username
                and t.created_at like :date
            ')
			->setParameter('username',$username)
			->setParameter('date',$date.'%');
	}

}
